# 2022/03/26

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  InjectDispatcher:
    active: true
    dispatcherNames: ['IO', 'Default', 'Unconfined']
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
#  SuspendFunWithCoroutineScopeReceiver:
#    active: true # todo
  SuspendFunWithFlowReturnType:
    active: true
