#!/bin/bash

if test $# -eq 0; then
 echo "Empty arguments!"; exit 11
fi

OPTION="$1"

case "$OPTION" in
 -eq)
  if test $# -ne 3; then
   echo "Script needs for 3 argument but actual $#"; exit 21
  fi
  EXPECTED="$2"
  ACTUAL="$3"
  for it in EXPECTED ACTUAL; do
   if test -z "${!it}"; then echo "$it is empty!" > $OUTPUT; exit 22; fi; done
  if test "${!EXPECTED}" != "${!ACTUAL}"; then
   echo "Actual is \"${!ACTUAL}\", but expected is \"${!EXPECTED}\"!"; exit 23
  fi;;
 -f)
  if test $# -ne 2; then
   echo "Script needs for 2 argument but actual $#"; exit 21
  fi
  FILE_PATH="$2"
  for it in FILE_PATH; do
   if test -z "${!it}"; then echo "$it is empty!" > $OUTPUT; exit 22; fi; done
  if [ ! -f "$FILE_PATH" ]; then
   echo "File $FILE_PATH does not exist!"; exit 21
  fi;;
 -d)
  if test $# -ne 2; then
   echo "Script needs for 2 argument but actual $#"; exit 21
  fi
  DIR_PATH="$2"
  for it in DIR_PATH; do
   if test -z "${!it}"; then echo "$it is empty!" > $OUTPUT; exit 22; fi; done
  if [ ! -d "$DIR_PATH" ]; then
   echo "Dir $DIR_PATH does not exist!"; exit 21
  fi;;
 *) echo "Option \"$OPTION\" is not supported!"; exit 91;;
esac
