name: Verify

on:
  workflow_dispatch:
    inputs:
      git_source:
        description: "GIT source name. For example [dev, wip...]."
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      VCS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
    steps:
      - run: |
          echo "HOME=$(echo ~)" >> $GITHUB_ENV
          echo "BUILD_PATH=$HOME/$(jq -r .workflow $GITHUB_EVENT_PATH | base64)/$GITHUB_RUN_NUMBER/$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "REPOSITORY_OWNER=$(jq -r .repository.owner.login $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(jq -r .repository.name $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "GIT_BRANCH_SRC=${{github.event.inputs.git_source}}" >> $GITHUB_ENV
          if test -z "$VCS_PAT"; then exit 21; fi
      - run: |
          mkdir -p $BUILD_PATH/repository
          git -C $BUILD_PATH/repository init
          git -C $BUILD_PATH/repository remote add origin https://$VCS_PAT@github.com/$REPOSITORY_OWNER/$REPOSITORY_NAME.git
          git -C $BUILD_PATH/repository fetch --depth=1 origin $GIT_BRANCH_SRC
          git -C $BUILD_PATH/repository checkout FETCH_HEAD
          cat "$BUILD_PATH/repository/.github/env" >> $GITHUB_ENV
      - run: |
          docker build --no-cache \
           --build-arg REPOSITORY_OWNER=$REPOSITORY_OWNER \
           --build-arg REPOSITORY_NAME=$REPOSITORY_NAME \
           --build-arg VERSION_CI_EXTENSION=$VERSION_CI_EXTENSION \
           --build-arg VCS_PAT=$VCS_PAT \
           --build-arg GIT_BRANCH_SRC=$GIT_BRANCH_SRC \
           -t image.verify:$GITHUB_RUN_NUMBER \
           -f $BUILD_PATH/repository/buildSrc/src/main/resources/docker/checkout.FETCH_HEAD.docker $BUILD_PATH/repository
      - env:
          TELEGRAM_BOT_ID: ${{secrets.TELEGRAM_BOT_ID}}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
        run: |
          echo "REPOSITORY_OWNER=$REPOSITORY_OWNER" > $BUILD_PATH/env
          echo "REPOSITORY_NAME=$REPOSITORY_NAME" >> $BUILD_PATH/env
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER" >> $BUILD_PATH/env
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID" >> $BUILD_PATH/env
          echo "TELEGRAM_BOT_ID=$TELEGRAM_BOT_ID" >> $BUILD_PATH/env
          echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID" >> $BUILD_PATH/env
          docker run --rm \
           -e VCS_PAT=$VCS_PAT \
           -e TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
           -e VCS_DOMAIN="$VCS_DOMAIN" \
           --env-file $BUILD_PATH/env \
           --name container.verify image.verify:$GITHUB_RUN_NUMBER \
           /bin/bash ex/workflow/verify/main.sh
