name: Verify

on:
  workflow_dispatch:
    inputs:
      git_source:
        description: "GIT source name. For example [dev, 087cc5a...]."
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      REPOSITORY_OWNER: kepocnhh
      REPOSITORY_NAME: useless
      VCS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
    steps:
      - run: |
          echo "HOME=$(echo ~)" >> $GITHUB_ENV
          echo "BUILD_PATH=$HOME/$(jq -r .workflow $GITHUB_EVENT_PATH | base64)/$GITHUB_RUN_NUMBER/$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "GIT_SOURCE=${{github.event.inputs.git_source}}" >> $GITHUB_ENV
      - run: |
          mkdir -p $BUILD_PATH/repository
          git -C $BUILD_PATH/repository init
          git -C $BUILD_PATH/repository remote add origin https://$VCS_PAT@github.com/$REPOSITORY_OWNER/$REPOSITORY_NAME.git
          git -C $BUILD_PATH/repository fetch --depth=1 origin $GIT_SOURCE
          git -C $BUILD_PATH/repository checkout FETCH_HEAD
      - run: |
          docker build --no-cache \
           --build-arg REPOSITORY_OWNER=$REPOSITORY_OWNER \
           --build-arg REPOSITORY_NAME=$REPOSITORY_NAME \
           --build-arg VCS_PAT=$VCS_PAT \
           --build-arg GIT_SOURCE=$GIT_SOURCE \
           -t image.verify:$GITHUB_RUN_NUMBER \
           -f $BUILD_PATH/repository/buildSrc/src/main/resources/docker/verify.docker $BUILD_PATH/repository
          echo "REPOSITORY_OWNER=$REPOSITORY_OWNER" > /tmp/build${GITHUB_RUN_NUMBER}.env
          echo "REPOSITORY_NAME=$REPOSITORY_NAME" >> /tmp/build${GITHUB_RUN_NUMBER}.env
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER" >> /tmp/build${GITHUB_RUN_NUMBER}.env
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID" >> /tmp/build${GITHUB_RUN_NUMBER}.env
          docker run --rm \
           -e VCS_PAT=$VCS_PAT \
           -e VCS_DOMAIN="https://api.github.com" \
           --env-file /tmp/build${GITHUB_RUN_NUMBER}.env \
           --name container.verify image.verify:$GITHUB_RUN_NUMBER \
           /bin/bash repository/buildSrc/src/main/resources/bash/workflow/verify/main.sh
