name: Verify

on:
  workflow_dispatch:
    inputs:
      git_source:
        description: "GIT source name. For example [dev, wip...]."
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      VCS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
    steps:
      - run: |
          echo "REPOSITORY_OWNER=$(jq -r .repository.owner.login $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(jq -r .repository.name $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "GIT_BRANCH_SRC=${{github.event.inputs.git_source}}" >> $GITHUB_ENV
          if test -z "$VCS_PAT"; then exit 21; fi
          mkdir -p repository
      - working-directory: repository
        run: |
          git init
          git remote add origin https://$VCS_PAT@github.com/$REPOSITORY_OWNER/$REPOSITORY_NAME.git
          git fetch --depth=1 origin $GIT_BRANCH_SRC
          git checkout FETCH_HEAD
          cat .github/env >> $GITHUB_ENV
      - working-directory: repository
        run: |
          docker build --no-cache \
           --build-arg REPOSITORY_OWNER=$REPOSITORY_OWNER \
           --build-arg REPOSITORY_NAME=$REPOSITORY_NAME \
           --build-arg VERSION_CI_EXTENSION=$VERSION_CI_EXTENSION \
           --build-arg VCS_PAT=$VCS_PAT \
           --build-arg GIT_BRANCH_SRC=$GIT_BRANCH_SRC \
           -t image.verify:$GITHUB_RUN_NUMBER \
           -f buildSrc/src/main/resources/docker/checkout.FETCH_HEAD.docker .
      - env:
          TELEGRAM: ${{secrets.TELEGRAM}}
        run: |
          docker run --rm \
           -e VCS_PAT=$VCS_PAT \
           -e VCS_DOMAIN=$VCS_DOMAIN \
           -e REPOSITORY_OWNER=$REPOSITORY_OWNER \
           -e REPOSITORY_NAME=$REPOSITORY_NAME \
           -e GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER \
           -e GITHUB_RUN_ID=$GITHUB_RUN_ID \
           -e TELEGRAM_BOT_ID="$(echo "$TELEGRAM" | base64 -d | jq -Mcer ".bot.continuousibot.id")" \
           -e TELEGRAM_BOT_TOKEN="$(echo "$TELEGRAM" | base64 -d | jq -Mcer ".bot.continuousibot.token")" \
           -e TELEGRAM_CHAT_ID="$(echo "$TELEGRAM" | base64 -d | jq -Mcer ".chat.kepocnhh.id")" \
           --name container.verify image.verify:$GITHUB_RUN_NUMBER \
           ex/workflow/verify/main.sh
